### ISSUE TITLE
index.html needs link to dev_timeline.html

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-website#10]
i think this blocks on @bbondy signing off on dev_timeline.html

should this go in the navbar? the navbar is getting pretty crowded

**Comment by bradleyrichter** [comment]
need to put a link to it at the bottom of the dev section.

**Comment by bbondy** [comment]
signed off.

**Comment by diracdeltas** [comment]
this depends on #9 but might be worth doing for now anyway?
