### ISSUE TITLE
iOS app requires www.brave.com/terms_of_use and it was removed

### ISSUE THREAD

**Issue by garvankeeley** [brave/brave-website#103]
If the url is being moved i can change it for new releases, but existing releases point to
 https://www.brave.com/terms_of_use

**Comment by bbondy** [comment]
@bradleyrichter can we get a redirect setup here?  Also, any time we change ANY URLs, we should preserve the old route in case people link to it. Thanks!

**Comment by garvankeeley** [comment]
In future, a better system is to have the apps make a REST-type call to ask for the endpoints for TOS and privacy.

**Comment by bbondy** [comment]
Any site can link to us, they won't use a similar REST call, so in any case we need to preserve old URLs if there's any chance someone is linking to it.

**Comment by garvankeeley** [comment]
closing, it has returned from the dead!
