### ISSUE TITLE
Footer contains vestigial classname

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-website#105]
![brave-site](https://cloud.githubusercontent.com/assets/815158/14554289/e2c18e38-02a0-11e6-829a-6c5414d4fb58.gif)

**Comment by bradleyrichter** [comment]
I was wondering where that DOT came from!



Thanks Jonathan!



Brad

**Comment by jonathansampson** [comment]
@bradleyrichter I would have issued a pull request, but the build instructions don't result in much success for us Windows users :)

**Comment by jonathansampson** [comment]
@bradleyrichter I'm still unable to get the Brave Server up and running on Windows 10, but the fix was trivial enough that I see no harm in building and issuing a pull request.

**Comment by jonathansampson** [comment]
Closing, as #106 has been implemented manually.

**Comment by bradleyrichter** [comment]
@jonathansampson thanks for closing. The fix was much easier than processing the pull request.  :    )
