### ISSUE TITLE
Blog RSS feed

### ISSUE THREAD

**Issue by cigitia** [brave/brave-website#107]
The Brave browser is a fascinating initiative. I use RSS feeds to keep up with websites, however; it would be great if the Brave blog provided an RSS feed. I don't want to miss any new posts.

Of course, there are probably higher-priority things to take care of. This would just be a nicety.

**Comment by jonathansampson** [comment]
I looked into taking a crack at this, but I'm presently blocked by #91. Brave Website presently is statically generated, so the RSS file would need to be built pre-commit, along with all of the other static files. Shouldn't be too terribly difficult once standing up a local server is better documented.

**Comment by bradleyrichter** [comment]
Rss should be coming soon via ghostblog as we switch over this week.

**Comment by jonathansampson** [comment]
@bradleyrichter That's wonderful news; does that also mean that all issues pertaining to the current templates are now obsolete, and good to close?

**Comment by jonathansampson** [comment]
@bradleyrichter Any update on the ghostblog deployment?

**Comment by bradleyrichter** [comment]
@jonathansampson 
https://blog.brave.com/

and the RSS:
https://blog.brave.com/rss/
