### ISSUE TITLE
UX On FAQ page is confusing

### ISSUE THREAD

**Issue by bbondy** [brave/brave-website#11]
You load page and all questions are expanded (good, please keep this).

But there's a link to re-open closed questions, even know all is already open. 

Click on an FAQ question and it collapses just that one question, click on the next one and it collapses just that one question. There seems to be no benefit to this.

Click twice on any individual question and it collapses all. 

I'm open to various approaches here but the current UX is pretty confusing and unexpected. 
Either of these approaches seems fine to me:
i) Don't allow collapsing, maybe add some more space between FAQ items.Optionally have a TOC up top which links down.
ii) Add a collapse all button, clicking twice on an individual FAQ item should toggle collapse / expand.

**Comment by bradleyrichter** [comment]
I tried to fix this problem before posting it initially. UX was best when you couldn't search. (but unacceptable tradeoff) Removing all controls and leaving it all open may be the only way without spending more time. @retzion LMK if you have any ideas for a fix.

**Comment by retzion** [comment]
I just took a look. 
Clicking twice is actually closing a section then opening it. Opening a section triggers all others to collapse. I can attach that close-all method to the collapse method so when you close one section, they all close.
We can hide the "re-op all closed" link until the collapse function is called. It will appear only when the divs collapse. This is theory until I jump into the scripts.

**Comment by bbondy** [comment]
I like what Brad suggested best.

**Comment by retzion** [comment]
Something like this? http://evarb.brave.com/FAQ.html

**Comment by bbondy** [comment]
Much better, thanks!

**Comment by bradleyrichter** [comment]
perfect. done. thanks!
