### ISSUE TITLE
Need left padding for newsletter form in the footer

### ISSUE THREAD

**Issue by serv** [brave/brave-website#113]
What do you think about adding 10px-ish left padding for the newsletter form?

### without padding
![screen shot 2016-05-14 at 2 30 46 am](https://cloud.githubusercontent.com/assets/103456/15267640/e568fb0c-197b-11e6-8b07-b73496169bc7.png)

### with 10px padding
![screen shot 2016-05-14 at 2 30 20 am](https://cloud.githubusercontent.com/assets/103456/15267637/d23cb532-197b-11e6-914e-c07bd2fa90b1.png)

**Comment by bradleyrichter** [comment]
good catch. thanks...

I'll add it when I next update the footer.

**Comment by bennyschmidt** [comment]
https://github.com/brave/brave-website/commit/5fa0a6a8958de6122a47a9e82185f0bf695bd109
