### ISSUE TITLE
OnAction while clicking

### ISSUE THREAD

**Issue by iamVP7** [brave/brave-website#118]
Visit https://brave.com/brave_youth_program.html
![onclick_braveyouth](https://cloud.githubusercontent.com/assets/3106852/17269672/9a032290-566c-11e6-8fa8-b4823ec6953e.png)

There is a map which lists Brave chapter in that page.
There is a button (round button) on map near American part. It appears to be click able.
On Click on that round button no action is there.

**Comment by bradleyrichter** [comment]
Thanks for the heads up.

I hid this until we have 3 spots to showcase.
