### ISSUE TITLE
needs csrf protection on signup form

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-website#12]
maybe something like https://github.com/hapijs/crumb

**Comment by retzion** [comment]
I'm having some trouble registering multiple plugins for hapijs.
There is a mod named Glue that should help.
https://github.com/hapijs/hapi/issues/2669
https://www.npmjs.com/package/glue
I'm getting that set up. 
@diracdeltas am on I the right track? Maybe I don't need glue to register crumb for only the api route? I hope to have it working before you get this message. ;)

**Comment by retzion** [comment]
request.state[settings.key] is returning null in crumb/lib/index.js line 156
https://github.com/hapijs/crumb/issues/50
