### ISSUE TITLE
Add smart zoom functionality

### ISSUE THREAD

**Issue by mattbontrager** [brave/brave-website#133]
The smart zoom feature (*two-finger double tap on trackpad*) in Safari is incredibly useful for those of us with less-than-great eye sight. I would use Brave a lot more if it had the same feature.

![](http://toolsdept.com/hosted-images/smart-zoom.gif)

**Comment by BrendanEich** [comment]
Thanks, Matt -- I'm sorry I didn't specify, but you should file this against https://github.com/brave/browser-laptop/ not against our website. I think @bridiver may know of a fix, if one isn't already on its way.

**Comment by mattbontrager** [comment]
Thanks Brendan. Got it filed in the correct place now. Thanks for all you do!
