### ISSUE TITLE
About Us in the page footer links to the about.html#team

### ISSUE THREAD

**Issue by srirambv** [brave/brave-website#144]
`About Us` in the page footer links to the about.html#team. 

All `About Us` link accross the site should point to https://www.brave.com/about.html

**Comment by jotasprout** [comment]
So this is taken care of?

**Comment by bradleyrichter** [comment]
no. thanks for the reminder.

**Comment by jotasprout** [comment]
I thought the commit referenced above in #151 stating it fixed issue #144 meant it was fixed. Is that incorrect? I was asking, really, to know if it was issue I could take on or if someone else was actively working on it.
