### ISSUE TITLE
Highlight on selection isn't consistent

### ISSUE THREAD

**Issue by bkjohnson** [brave/brave-website#147]
I was checking your site out in Chrome and thought that what you are doing with selected text is a really great subtle touch that works well with your theme:

![screenshot from 2016-11-04 17-31-01](https://cloud.githubusercontent.com/assets/2008881/20024436/905c2a72-a2b4-11e6-8242-9141f192b830.png)

### Problem
However, I was a little disappointed to see that the effect only worked on white backgrounds:

![screenshot from 2016-11-04 17-34-19](https://cloud.githubusercontent.com/assets/2008881/20024486/f0e764ec-a2b4-11e6-94fb-adba6e67b4bc.png)

![screenshot from 2016-11-04 17-33-11](https://cloud.githubusercontent.com/assets/2008881/20024457/c7c950a2-a2b4-11e6-99fb-828f7167582c.png)

Also, it doesn't work at all in Firefox:

![screenshot from 2016-11-04 17-37-39](https://cloud.githubusercontent.com/assets/2008881/20024564/6dca404c-a2b5-11e6-8de3-7355473f29c0.png)

### Solution
The fix for this would be to replace [this line](https://github.com/brave/brave-website/blob/0996780f64bd1d0e88d94c16f8be1de6ee95e99c/public/assets/css/one.style.css#L110) with `background: transparent;` and update the selector with `::selection, ::-moz-selection` so that it looks like this:
```
::selection, ::-moz-selection {
  color: #ff6c00;
  background: transparent;
}
```
Is this something I can submit a PR for, or do you prefer your website updates to come from team members only?

**Comment by bradleyrichter** [comment]
@bkjohnson nice find. A PR would be great!

**Comment by bkjohnson** [comment]
Thanks!  Also FWIW, my CSS snippet above was wrong.  You can't have `::selection` and `::-moz-selection` grouped together with a comma, they must be separate in order for the browser to recognize them.

**Comment by bradleyrichter** [comment]
@bkjohnson Can you please confirm the fix on staging.brave.com. Then we can push it to master as well.

**Comment by bkjohnson** [comment]
Just confirmed.  Highlighting works as expected on non-white and on Firefox and Chrome.  :+1:
