### ISSUE TITLE
piwik privacy improvements

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-website#156]
1. add the following tag to the privacy policy page to allow  users to opt out of analytics:
```
<iframe style="border: 0; height: 200px; width: 600px;" src="https://analytics.brave.com/index.php?module=CoreAdminHome&action=optOut&language=en"></iframe>
```

2. enable DNT client-side support (we already support the header) by replacing the existing piwik code with:
```
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(["setDomains", ["*.brave.com"]]);
  _paq.push(["setDoNotTrack", true]);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//analytics.brave.com/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 2]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//analytics.brave.com/piwik.php?idsite=2" style="border:0;" alt="" /></p></noscript>
<!-- End Piwik Code -->
```

**Comment by mrose17** [comment]
notes: at some point we should upgrade piwik

**Comment by diracdeltas** [comment]
cc @w0ts0n in case this can be done while upgrading piwik

**Comment by w0ts0n** [comment]
I didn't change any code site side, sorry!

I believe brad already tried 1. and it broke some stuff/looked bad. That might have changed now we've updated piwiki so may be worth another attempt.

**Comment by jonathansampson** [comment]
I don't specifically recall being involved in a piwik effort; @bradleyrichter, sound familiar?

**Comment by w0ts0n** [comment]
1. is an issue. The iframe method is ugly as sin and also not great practice. 
Thinking about alternatives and pinged Yan with some suggestions. 

2. is done.

**Comment by w0ts0n** [comment]
Okay, after getting the all clear from brad/yan I just put a little blurb to the URL to opt-out. Happy compromise.
