### ISSUE TITLE
Alternative iconography

### ISSUE THREAD

**Issue by jamesgrayillustration** [brave/brave-website#16]
Hi, I was inspired by your new browser and so I mocked up some icons/branding.

Some examples:

![braveconcepts_pres2-01](https://cloud.githubusercontent.com/assets/4734952/12539101/19a16734-c2b9-11e5-888f-e559a566d17e.png)

![braveconcepts_pres2-05](https://cloud.githubusercontent.com/assets/4734952/12539105/1ecc7b4a-c2b9-11e5-942e-2b2f71885ffa.png)

[Here's the Dropbox Folder with more mockups](https://www.dropbox.com/sh/tkugke1fx1tia1e/AAAd__HoOYrCEsErT57r1S3Oa?dl=0).

Let me know if you're interested - I can provide the Illustrator files.

:+1:

**Comment by bradleyrichter** [comment]
Hi James - thanks for the submission. Very unique approach to the lion profile. One of the first I have seen that doesn't at all resemble a sports team which is what we found when exploring profiles. I think we will stay what we currently have for a while but thanks again for the submission....Brad

**Comment by bbondy** [comment]
Cool to see the alternate approach and identity @jamesgrayillustration

**Comment by bradleyrichter** [comment]
Absolutely.
