### ISSUE TITLE
Make CSP frame-ancestors directive possible on Hapi

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-website#162]
Looking at [Hapi docs](https://hapijs.com/api), allowing `frame-ancestors` directive is not possible without plugins. 

`x-frame-options` is currently set to deny so it's not possible to load an iframe from brave.com. 
 Source rule for x-frame could be applied but is not possible because we're asking to allow a `chrome-extension` url, so the header is ignored - not recognized as a directive. Also tagged as [`wont-fix`](https://bugs.chromium.org/p/chromium/issues/detail?id=129139) from Chromium. 

Only way would be to override rule using `frame-ancestors`.

This is needed to create about:welcome on browser-laptop (see https://github.com/brave/browser-laptop/issues/7821).

/cc @bridiver @diracdeltas

**Comment by hueniverse** [comment]
I assume you need to change these:
https://github.com/hapijs/hapi/blob/master/lib/schema.js#L147-L154
https://github.com/hapijs/hapi/blob/master/lib/route.js#L199-L218

To allow for this rule to generate the header you want.

**Comment by cezaraugusto** [comment]
@hueniverse we need an option to set `Content-Security-Policy: frame-ancestors <source>`. Actually `frame-ancestors` [would overlap](https://www.w3.org/TR/CSP2/#frame-ancestors-and-frame-options) `x-frame-options`. So it should be set inside `security` but not as part of `xframe` API.

What's happening is that we have `x-frame-options` on brave.com set to "deny", which should work with a given source by allowing it using `ALLOW-FROM`. However the source we want is a `chrome-extension` url (`chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/about-welcome.html`), and Chromium doesn't support it (tagged as [wontfix](https://bugs.chromium.org/p/chromium/issues/detail?id=129139)). My guess that `frame-ancestors` would work with that.

**Comment by hueniverse** [comment]
@cezaraugusto So your plan is to disable the `x-frame-options` headers completely and instead use the `Content-Security-Policy: frame-ancestors <source>` header?

**Comment by diracdeltas** [comment]
@cezaraugusto just to clarify, if you set CSP frame-ancestors to just the chrome-extension origin, you will no longer need the x-frame-options header AFAIK.

seems like https://github.com/nlf/blankie will do the trick, thanks @hueniverse

**Comment by hueniverse** [comment]
Let me know if you need further assistance.

**Comment by cezaraugusto** [comment]
Thanks all, issue solved
