### ISSUE TITLE
HTTP brave.com links on new site need to be HTTPS

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-website#178]
* big download button goes to http://brave.com/downloads.html
* 'support' link goes to http://community.brave.com

may be others

**Comment by alexwykoff** [comment]
About page 
- Sampson's profile - http://sampson.ms/
- Lawler's profile - http://twitter.com/kevinlawler
                             - http://kevinlawler.com/

**Comment by diracdeltas** [comment]
^ some of those pages may not support https but twitter definitely does
