### ISSUE TITLE
Publishers page footer links are inconsistent with other pages

### ISSUE THREAD

**Issue by alexwykoff** [brave/brave-website#180]
https://brave.com/publishers/ has some links which don't match

Terms of Use - https://brave.com/terms-of-use_6/

Privacy - https://brave.com/privacy_7/

**Comment by LaurenWags** [comment]
If you click on those, you get 'No results found'. Similarly with https://brave.com/about/ which has 

Terms of Use - https://brave.com/terms-of-use_2/

Privacy - https://brave.com/privacy_3/

**Comment by LaurenWags** [comment]
Also on https://brave.com/download/ (no results found for these either)

Terms of Use - https://brave.com/terms-of-use_1/

Privacy - https://brave.com/privacy_1/

**Comment by LaurenWags** [comment]
Also on https://brave.com/jobs/

Terms of Use - https://brave.com/terms-of-use_3/

Privacy - https://brave.com/privacy_4/

**Comment by LaurenWags** [comment]
Also on https://brave.com/faq/#brave-payments

Terms of Use - https://brave.com/terms-of-use_5/

Privacy - https://brave.com/privacy_6/

**Comment by bradleyrichter** [comment]
these are fixed. please confirm and close. TY!

**Comment by LaurenWags** [comment]
They all look good to me!
