### ISSUE TITLE
Media Assets are not links

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-website#181]
When on the About page and in the Media Assets section, Brave Logo Files, Brave Icon Files, Infographics, and Partner Badges are not links.

Nav to https://brave.com/about/
Find Media Assets.
Nothing in this area is clickable.

**Comment by bradleyrichter** [comment]
@LaurenWags fixed and ready for confirmation

**Comment by LaurenWags** [comment]
Confirmed all 4 are clickable.
