### ISSUE TITLE
Broken link for Brave Badge

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-website#182]
'Final Step' at https://brave.com/publishers/#getverified has a broken link, 'Brave Badge' link directs you to https://brave.com/publishers/about_1.html#media-assets where no results found.

Nav to https://brave.com/publishers/#getverified
Locate the 'Final Step'
Click on 'Brave Badge'

**Comment by bradleyrichter** [comment]
@LaurenWags this is fixed if you would like to confirm and close.

**Comment by LaurenWags** [comment]
Looks good!
