### ISSUE TITLE
Footer logo at the left hand side is missing

### ISSUE THREAD

**Issue by serv** [brave/brave-website#19]
<img width="1023" alt="screen shot 2016-01-25 at 11 26 36 pm" src="https://cloud.githubusercontent.com/assets/103456/12574702/1d281ddc-c3bb-11e5-81b1-7687ff77edeb.png">

Footer logo on the left hand side is missing.
It looks like `assets/img/brave_logo_icon_grey.png` is missing. See https://github.com/brave/brave-website/blob/master/public/index.html#L672

**Comment by bradleyrichter** [comment]
thanks for the heads up @serv 

@retzion - I saw it on staging. Can you check it?

**Comment by retzion** [comment]
Maybe someone fixed this.
http://evarb.brave.com/assets/img/brave_logo_icon_grey.png
Is that the right image? Small and greyscale?

**Comment by retzion** [comment]
Oh, sorry, you said you saw it on staging. We need to merge to master in the next few hours anyway.

**Comment by serv** [comment]
Looks like this is fixed. Closing.
