### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by serv** [brave/brave-website#21]
Is a license needed for this repository like browser-laptop repository?
If so, is the [Mozilla Public License Version 2.0](https://github.com/brave/browser-laptop/blob/master/LICENSE.txt) sufficient?

**Comment by bbondy** [comment]
Sure let's do LICENSE.txt from the brave/browser-laptop, pull request would be welcome. Thanks!

**Comment by serv** [comment]
Closing this issue as it is resolved now. Thanks @bbondy
