### ISSUE TITLE
Web compat issues with header link dividers

### ISSUE THREAD

**Issue by KevinGrandon** [brave/brave-website#24]
It seems the top bullets are sized differently in Chrome vs Firefox.

<img width="1296" alt="2016-01-27 8 47 26" src="https://cloud.githubusercontent.com/assets/122602/12635360/3b05a2f2-c537-11e5-9891-9ad39d11db26.png">

**Comment by bennyschmidt** [comment]
bullet points were dropped in the recent redesign, thanks
