### ISSUE TITLE
Needs higher version of Hapi

### ISSUE THREAD

**Issue by greggawatt** [brave/brave-website#38]
I need a bit of help, i'm trying to fix an issue with the site and NPM install gives me this warning that i can't seem to solve:

```
npm WARN lifecycle brave-website@0.0.1~postinstall: cannot run in wd %s %s (wd=%s) brave-website@0.0.1 gulp /Users/gregg/development/brave-website
npm WARN EPEERINVALID crumb@6.0.0 requires a peer of hapi@>=12.x.x but none was installed.

```
Any thoughts?

Node: v5.4.1
NPM: 3.3.12

**Comment by bradleyrichter** [comment]
@diracdeltas Can you please assist Greg?

**Comment by diracdeltas** [comment]
pretty sure if you do `npm update` it will install hapi >12. should probably change `package.json` to require a higher hapi version. thanks.

**Comment by greggawatt** [comment]
Changing the version in `package.json` fixed it, thanks!

**Comment by diracdeltas** [comment]
cool, please commit the changes and open a pull req

**Comment by diracdeltas** [comment]
nvm, i see it in https://github.com/brave/brave-website/pull/39/files. thanks
