### ISSUE TITLE
Add open graph title and description for sharing

### ISSUE THREAD

**Issue by bbondy** [brave/brave-website#4]
Please also add open graph meta tags with a title and description so FB doesn't have to infer from parsing the page what to use.

more info here:
http://ogp.me/#metadata

**Comment by serv** [comment]
@bbondy Can you provide the title and description you'd like for the og meta tags?
Also it looks like the page is missing description meta. 

`<meta name="description" content="">` 

Is it ok to go with the same description here?

**Comment by bbondy** [comment]
@bradleyrichter or @ElissaBeth can get you that, thanks for helping out!
