### ISSUE TITLE
Brave opens inside of my taskbar [enhancement]

### ISSUE THREAD

**Issue by muffinscat** [brave/brave-website#41]
Hi, so I like to put my taskbar at the top of my monitor, but whenever I open brave, it is inside of the taskbar, with the gap at the bottom. Other programs don't do this so I know it's not on my end so I was wondering if this could be changed.

**Comment by muffinscat** [comment]
Also just little stuff like I can't use mouse4 and mouse5 to go forward and backward but I know this is all in development

**Comment by diracdeltas** [comment]
please open at https://github.com/brave/browser-laptop instead, thanks.
