### ISSUE TITLE
Browser crashes on new tabs

### ISSUE THREAD

**Issue by matthew-field** [brave/brave-website#49]
So I was reading my emails in the browser and everything worked fine. I got to one of my HuffPost emails and clicked a link to their articles and the browser crashed. Re-opened, tried again, same result.

**Comment by bbondy** [comment]
I think you want this repo:
https://github.com/brave/browser-laptop 

Also please check that you have 0.7.12 which should already fix that.  Please repost if it's an issue with 0.7.12 there. Thanks.
