### ISSUE TITLE
Social icons on profiles can't be accessed on mobile devices

### ISSUE THREAD

**Issue by bbondy** [brave/brave-website#5]
There's no hover event so profiles can't be accessed. 
Quick fix might be to just add a link handler on the image itself to the first profile.

**Comment by serv** [comment]
I agree with @retzion's approach. Since we are using bootstrap, we can do something like this.
http://getbootstrap.com/css/#responsive-utilities

**Comment by retzion** [comment]
Shall I implement this approach, @bbondy? If so, please assign me the task.

**Comment by bbondy** [comment]
sgtm, CCing @bradleyrichter in case that's a problem.

**Comment by bradleyrichter** [comment]
@retzion works for me. Tiny but large enough to tap...

**Comment by retzion** [comment]
staged: https://evarb.brave.com/#team

**Comment by retzion** [comment]
![simulator screen shot jan 28 2016 10 45 34 pm](https://cloud.githubusercontent.com/assets/1813451/12668493/5ecbe45c-c614-11e5-8df3-3478b758b572.png)

I just noticed that after tapping a social network icon the layer above the team member photo appears. I can hide that via css !important.

**Comment by retzion** [comment]
I hide the layer above the profile photos for mobile widths.
