### ISSUE TITLE
Brave goes back to previous web page while pressing backspace key in Youtube comment on Windows 8

### ISSUE THREAD

**Issue by vasanth1986** [brave/brave-website#51]
Steps to reproduce:
1. Open Youtube.com and select any video to playback.
2. Go to comment section and type a new comment then press Backspace key.
3. Observe that Brave goes back to previous web page instead only deleting the typed texts.

Actually typed texts are deleting and Brave goes back to previous web page.

- Vasanth

**Comment by bennyschmidt** [comment]
@vasanth1986 This is the marketing site repo. If this is still an issue, please open it here https://github.com/brave/browser-laptop/issues Thank you (and sorry for the delay!)
