### ISSUE TITLE
List Linux as an option on the signup dev form

### ISSUE THREAD

**Issue by bbondy** [brave/brave-website#6]
From support.

> I've just signed up for the Beta program and was a bit annoyed when, 
while filling out the application form, there was no option for a 
GNU/Linux based OS or even an "other" category. Would you please correct 
this?

**Comment by diracdeltas** [comment]
agree, we are getting a lot of interested linux people

**Comment by retzion** [comment]
@ElissaBeth tells me we aren't going to add Linux as an option just yet.

**Comment by bbondy** [comment]
++ for adding Linux even know we won't produce builds yet. 
We're missing out on emails right now for people who would be interested to hear about our milestones.

**Comment by diracdeltas** [comment]
agree with ^
