### ISSUE TITLE
Display Issue on Mobile for brave.com

### ISSUE THREAD

**Issue by ElissaBeth** [brave/brave-website#64]
Large grey unformatted area with no text. 
Fix in one place will fix across the board.

**Comment by ElissaBeth** [comment]
Pull requests to fix this are welcome. :)

**Comment by ElissaBeth** [comment]
it’s a margin or padding problem in a container div

**Comment by ElissaBeth** [comment]
Someone is working on this now.

**Comment by viswanathamsantosh** [comment]
Hey @ElissaBeth , is this issue fixed or should i work on it?

**Comment by bradleyrichter** [comment]
Hi @viswanathamsantosh - we are getting some site changes in for these new meetup events which should fix this issue. Thanks for the reminder!

Brad

( @ElissaBeth )
