### ISSUE TITLE
Add a report an issue on this site link to the footer somewhere

### ISSUE THREAD

**Issue by bbondy** [brave/brave-website#7]
It should link to:
https://github.com/brave/brave-website/issues/new

**Comment by bradleyrichter** [comment]
this is for any brave issue or web site issues?

**Comment by bbondy** [comment]
Please emphasize a problem with the site only 
Or if you want it can link to a page that describes the different repo issues links.

**Comment by diracdeltas** [comment]
fixed in https://github.com/brave/brave-website/commit/86028c1a423af490e1ab40d478033315aabb0643. i had it go to the issues list instead of automatically opening a new issue hoping this would reduce duplicated issues.
