### ISSUE TITLE
Clearly State 64-bit Only

### ISSUE THREAD

**Issue by Ken-Saunders** [brave/brave-website#80]
Clearly state on the site that the Brave browser (for Desktop and Laptop) is for 64-bit OS's (only).

My opinions:
It's necessary to do this to save time and frustration for 32-bit OS users (like myself) attempting to install the Brave browser that is for 64-bit OS's. Not doing so could potentially anger potential Brave consumers enough to write off Brave completely and permanently (myself not included), which of course is a lose-lose since they could always use the future mobile version or, install Brave when they upgrade their PC's.

If there truly will be a 32-bit version, then add some statement or documentation somewhere saying that the Brave browser (for Desktop and Laptop) is -currently- for 64-bit OS's only but there will be a 32-bit version in the future. If there won't be, explain why there won't be and/or, encourage site visitors to "Sign up to be notified..." when a mobile version will be ready.

**Comment by bbondy** [comment]
Sorry for this oversight, it should definitely say Win x64 on the website. CC @ElissaBeth

**Comment by Ken-Saunders** [comment]
Thank you, but an apology is certainty not necessary. 
It's still very early and y'all are busy.

**Comment by bradleyrichter** [comment]
@Ken-Saunders Hi Ken - looking at the update to the web site, do you feel this would have given you the info you needed regarding x64?

![image](https://cloud.githubusercontent.com/assets/13509546/13224434/68071e74-d93d-11e5-92ff-5cd9960eeb5b.png)

**Comment by Ken-Saunders** [comment]
> do you feel this would have given you the info you needed regarding x64?

Yes, and if I were someone else really wanting to try/use Brave, I'd still look for 32-bit and the Android & more button (Sign up to be notified) kind of tells you that it isn't (yet?) available. That's something that I didn't bother with initially since I (wrongly) assumed that Brave was compatible with my system. 

In my opinion, it's good enough for now but in the future when there's even more interest, traffic, and a release version, if 32-bit versions won't be available, that should be more clear by at the least be stated on a system requirements page.

Thanks for taking care of this.

**Comment by bradleyrichter** [comment]
thanks. closing for this version of the web site.

**Comment by brilvio** [comment]
@bradleyrichter Hi there I think this issue have to be reopen, because in the site this moment it doesn't say anywhere that the setup is for Windows 64 only, I downloaded and tried to install and I was having problems so I had to search in the issues for this problem. Not everybody is a developer and not everybody will search for the problem. Keep that in mind.
![brave](https://cloud.githubusercontent.com/assets/4560552/14315869/2fb5782a-fbd6-11e5-907c-318933d998bb.png)

**Comment by bbondy** [comment]
thanks @brilvio

**Comment by bradleyrichter** [comment]
doh! New site makover killed last fix. Will fix again asap. @brilvio Thanks for the headsup.

**Comment by brilvio** [comment]
No problem at all.

**Comment by bennyschmidt** [comment]
platform strings for 32/64 bit (and everything else) were set up here https://github.com/brave/brave-website/commit/6a5b0157dc8301519a888a2ab2aedfa8297b6076
