### ISSUE TITLE
Typo in newsletter confirmation

### ISSUE THREAD

**Issue by Ken-Saunders** [brave/brave-website#81]
Typo is "newletter"
#mailchimpNewsletterConfirmationModal > DIV > DIV > DIV:last-child > DIV > IMG

![typo](https://cloud.githubusercontent.com/assets/1267130/13086264/7851caf4-d4b0-11e5-92b8-bbaf03fbf47a.png)

**Comment by bradleyrichter** [comment]
@Ken-Saunders Thanks for pointing out this unfortunate little error. We'll be sure to fix it!

**Comment by AkshayTiwari** [comment]
I've fixed the typo and pulled a request. 
https://github.com/brave/brave-website/pull/102 

Merge pending.
