### ISSUE TITLE
Polish characters

### ISSUE THREAD

**Issue by CNK001** [brave/brave-website#82]
I can't write some polish characters, eg. "ś" - when I press "alt" + "s" new card is opened :(

**Comment by bradleyrichter** [comment]
Since my wife is Polish, I thought I would test this one...  :   )

I can't reproduce on Mac OS X. See alternative ß caracter in two places:

@diracdeltas  - Perhaps it's a windows only bug?

![screen shot 2016-02-22 at 7 20 09 am](https://cloud.githubusercontent.com/assets/13509546/13222524/1b73d0aa-d935-11e5-90ee-50e677dfdfdf.png)

**Comment by CNK001** [comment]
I have Windows 10 😉

**Comment by diracdeltas** [comment]
@CNK001 that's weird, i don't think alt+s is mapped to anything. Do you mean ctrl+alt+s? (mapped to new session tab.)

**Comment by CNK001** [comment]
No, only Alt + S. 
When i press "Alt" and "s" it opens new tab.

**Comment by diracdeltas** [comment]
alt+s on OS X renders ß not ś. according to some forum posts, right-alt+s should produce ś. maybe right-alt is being treated like ctrl+alt on windows? cc @bbondy

**Comment by CNK001** [comment]
Hmm.. It's right Alt + s on Windows and Mac OS. I use Polish (Programmers) Keyboard Layout AKA "Polish Pro".

![image](https://cloud.githubusercontent.com/assets/16397823/13236652/150196f8-d9c6-11e5-8acf-4cd8d7377312.png)

![image](https://cloud.githubusercontent.com/assets/16397823/13236635/fbd3dfce-d9c5-11e5-86ff-d47068b30b01.png)

![image](https://cloud.githubusercontent.com/assets/16397823/13236816/37261cc6-d9c7-11e5-82a7-a9898cd62c19.png)
http://www.theworldofstuff.com/characters/


This is similar to my issue: https://github.com/adobe/brackets/issues/6095

**Comment by diracdeltas** [comment]
BTW, just realized this is supposed to be in the browser repo, not the website repo. I'll link to it there.
