### ISSUE TITLE
Alto consumo de RAM

### ISSUE THREAD

**Issue by lcastroGT** [brave/brave-website#87]
Los procesos que se corren al ejecutar el navegador llegan a consumir, en total, 1115244 KB en RAM. Mencionando que solo se tienen abiertas 4 pestañas. 
![brave_ram](https://cloud.githubusercontent.com/assets/5115058/13474808/4a1d6518-e085-11e5-85ea-0bdd4867888a.png)

**Comment by marti1125** [comment]
Hi @lcastroGT creo que debes abrir un issue en el siguiente repo: https://github.com/brave/browser-laptop and in english please =D
