### ISSUE TITLE
Add win7+ specifier to the windows download link

### ISSUE THREAD

**Issue by bbondy** [brave/brave-website#88]

**Comment by jonathansampson** [comment]
@bbondy Was this issue resolved by https://github.com/brave/brave-website/commit/940dcbdc11ee542920be18e668a38439b6d00dba?

![image](https://cloud.githubusercontent.com/assets/815158/14593188/1ca564de-04dc-11e6-9aa5-29461ec8b5ea.png)

Or does the issue refer to the links towards the bottom of brave.com?

![image](https://cloud.githubusercontent.com/assets/815158/14593240/f0d3f586-04dc-11e6-901b-f4c53aea69ea.png)

**Comment by jonathansampson** [comment]
@bbondy *bump*

**Comment by bbondy** [comment]
seems like it can be closed now.
