### ISSUE TITLE
dev_timeline.html layout messed up on mobile

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-website#9]
![screen shot 2016-01-22 at 17 25 05](https://cloud.githubusercontent.com/assets/549654/12527259/20cf0a12-c12d-11e5-8d65-698a616fc550.png)

dev/beta/stable should be aligned with their respective release numbers

I think this needs to be a proper table, not a series of lists

**Comment by bradleyrichter** [comment]
@diracdeltas html table?

**Comment by diracdeltas** [comment]
@bradleyrichter yep, html table
