### ISSUE TITLE
Screen Goes Black

### ISSUE THREAD

**Issue by retierney** [brave/brave-website#92]
No one ever does this sort of thing except me. Go to **brave.com**, then pick any image that isn't hyperlinked (like the lion), and then drag and drop it off it's original location. For me, the **brave** window goes all black and has to be restarted. 

HP Pavilion dv7 laptop
Windows 7 SP 1 x64

**Comment by jonathansampson** [comment]
Wrong repo. Try [one of these instead](https://github.com/brave/browser-laptop/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+black).
