### ISSUE TITLE
"Tabs per page" text box is a pain to type in

### ISSUE THREAD

**Issue by OeBoe** [brave/brave-website#93]
Try typing in the number 12 to the tabs per page option in preferences.

As soon as you type the 1, it defaults to 3 because one tab per page is below the minimum.
As soon as you then type the 2, it defaults to 20 because 32 tabs per page is above the max.

You can get there by spamming the arrows, but that's not user friendly.

**Comment by jonathansampson** [comment]
@OeBoe This is the wrong repo for Brave app feedback. See instead https://github.com/brave/browser-laptop/issues.
