### ISSUE TITLE
Subtitles are unreadable on Safari

### ISSUE THREAD

**Issue by lucasmazza** [brave/brave-website#94]
![](https://dl.dropboxusercontent.com/s/8sothrjm6v8zjld/2016-04-02%20at%209.51%20PM.png)

Fiddling with the inspector looks like the `font-weight: 200` used on several subtitles don't play well with Safari, and even on other browsers (Chrome or Firefox) it might make it harder for folks with more serious sight issues.

**Comment by bennyschmidt** [comment]
@lucasmazza fixed this (changed to `font-weight: 400` for now and updated the size in a couple other spots). thank you for pointing it out :)
