### ISSUE TITLE
Homepage Hero Image

### ISSUE THREAD

**Issue by anistuhin** [brave/brave-website#97]
Home page hero image can be made more nicer by giving it a 100vh height and keeping all the info inside the screen. Is it okay to make the change and then send pull request??

**Comment by bennyschmidt** [comment]
@anistuhin that would be great :) go ahead and submit your PR and please mention me in the description. is your idea for larger screens to have a `max-height`, or would it always fill the viewport-height regardless of how tall? thanks.

**Comment by anistuhin** [comment]
Primarily it will fit the viewport-height, but it will definitely have a max-height :) Btw, it's open to make PR for any visual improvement right??

**Comment by bennyschmidt** [comment]
@anistuhin for optimizations like this, definitely! if it's a bigger design change, please make it a separate issue and mention @bradleyrichter with the details, and attach a mockup or screenshot of the suggested change so it can be reviewed, thanks.

**Comment by bennyschmidt** [comment]
@anistuhin implemented your `height: 100vh` solution. thank you for the suggestion!
